---
title: "Nexus X-Ray"
author: "Ship-It-Team 2018"
date: "9 März 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Convenience method that makes sure all required
# packages are present
installAndLoad <- function(package){
  if(!eval(parse(text=paste("require(",package,")")))) 
  { 
    install.packages(package, repos = "https://cran.uni-muenster.de/")
    eval(parse(text=paste("require(",package,")")))
  }
}

installAndLoad("ggplot2") # Charts
installAndLoad("ggthemes") # Nice charts
installAndLoad("grid") # Chart-Layout
installAndLoad("scales")
installAndLoad("wordcloud")
installAndLoad("tm") # um keine Frequenzen für Wordcloud vorbereiten zu müssen
installAndLoad("dplyr") # Filter und joins
source("viadeeTheme.R")

# Annahme: Der Zeitstempel in der CSV-Datei ist mit deutscher Locale formatiert.
entries <- read.csv("../../../data/entries.csv", sep=",")
entries$Creation.Date <- as.Date(substr(entries$Creation.Time,1,10), format="%d.%m.%Y")


```

## Was ist im Nexus zu finden?

Als erstes wird ein grober Überblick des zeitlichen Ablaufs erstellt. Ein Balken steht dabei für eine Woche.


```{r timeSeries}

viadee(ggplot()) +
  geom_histogram(
    data=entries, 
    aes(x=entries$Creation.Date), 
    binwidth=7,
    color="white",
    fill="white",
    alpha=0.6) +
  theme_economist()+
  scale_y_continuous(labels = comma)+
  labs(
    title="Nexus artefacts by create date",
    x ="Creation Date", y = "Number of artefacts")


```

```{r doesDeletionWork}

viadee(ggplot()) +
  geom_histogram(
    data=entries, 
    aes(x=entries$Creation.Date, fill=entries$Deleted), 
    binwidth=7,
    color="white",
    alpha=0.6) +
  theme_economist()+
  scale_y_continuous(labels = comma)+
  labs(
    title="Nexus artefacts by create date",
    x ="Creation Date", y = "Number of artefacts")

```

```{r sizeScaling}

viadee(ggplot()) +
  geom_histogram(
    data=entries, 
    aes(x=entries$Creation.Date, fill=entries$Deleted, weight=entries$Size), 
    binwidth=7,
    color="white",
    alpha=0.6) +
  theme_economist()+
  scale_y_continuous(labels = comma)+
  labs(
    title="Nexus artefacts by create date (size-scaled)",
    x ="Creation Date", y = "Size of artefacts (byte)")

```

```{r tagCloud}

  ourEntries <- entries %>% 
    filter(entries$Repository.Name %in% c("maven-snapshots", "maven-releases"))  

  wordcloud(words=ourEntries$Maven.Group)
  wordcloud(words=ourEntries$Maven.Artifact)
  
  ourArtifacts <- ourEntries %>%
    group_by(Maven.Artifact) %>%
    summarise(MegaBytesUsed = sum(Size / 1024 / 1024))
  
  viadee(ggplot(ourArtifacts)) +
      geom_bar(aes(x=reorder(ourArtifacts$Maven.Artifact, ourArtifacts$MegaBytesUsed), 
                   y=ourArtifacts$MegaBytesUsed), 
               colour="white", alpha=0.2, stat="Identity") +
      labs(title = "Leaderboard - Wer verwendet Nexus-Speicherplatz?",
           x = "Maven Artifacts", y = "MB")+
    coord_flip()

```